[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_tutorial = "71CGpNHh9383Un2LSUdDhHHDuZZhiKWvGHcXUUukVhWW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nanonano/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
